spring.application.name=app
spring.datasource.url=jdbc:postgresql://localhost:5432/VaultCore_db
spring.datasource.username=vlt_emp1
spring.datasource.password=VaultCore@123

spring.jpa.hibernate.ddl-auto=none

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.dao=TRACE
server.port=8080